spring:
  application:
    name: tech-interview-project

  # ?? ????? local
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  # JPA ?? ??
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        # Hibernate ?? (?? ??? ???)
        generate_statistics: false
    open-in-view: false

  # Jackson ??
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

  # ?? ??? ??
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# ?? ?? ??
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  shutdown: graceful

# Actuator ?? ??
management:
  endpoints:
    web:
      base-path: /actuator
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

# Logging ?? ??
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 30

# Swagger/OpenAPI ?? ??
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true

# JWT ?? ?? (???, ???? ????? ??)
jwt:
  access-token-validity: 1800000        # 30?
  refresh-token-validity: 604800000     # 7?

# Resilience4j Circuit Breaker ?? ??
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3

  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 1000
