server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:kboard;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web.servlet.view: debug   # (선택) ViewResolver 디버그
