spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          time_zone: UTC
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: ABSDFSASDFQWERQWEQREWRDAFSDKFQHPOIWERUQWEOIWEKSAFLDSFJKHDFPQEWRQWERWEQIRUWEQRWIOERQPWORIU
  access-token-seconds: 1800      # 30?
  refresh-token-seconds: 1209600  # 14?

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    com.example.auth: DEBUG

# CORS ?????? ?? (??? ?? ??)
app:
  cors:
    allowed-origins: "http://localhost:5173"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
