spring:
  # === DB (Prod) ===
  datasource:
    url: ${DB_URL}           # 운영은 반드시 ENV로 주입 (기본값 미지정)
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate     # 운영에서는 스키마 자동 수정 금지

  # === Redis (Prod) ===
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
  # 캐시 TTL은 공통(application.yml)에서 지정됨. 운영에서 다르게 쓰려면 override 하세요.
  cache:
    redis:
      time-to-live: ${CACHE_TTL_MS:600000}

server:
  port: ${PORT:8080}
  compression:
    enabled: true
    min-response-size: 2KB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus   # 프로메테우스 사용 시
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      probes:
        enabled: true  # k8s liveness/readiness 프로브용
      show-details: when_authorized

security:
  jwt:
    secret: ${JWT_SECRET}    # 운영은 ENV/시크릿 필수
    access-token-ttl-seconds: ${ACCESS_TTL:3600}
    refresh-token-ttl-seconds: ${REFRESH_TTL:1209600}

external:
  news:
    base-url: https://newsapi.org/v2
    api-key: ${NEWS_API_KEY}  # 운영은 ENV/시크릿 필수
    default-page-size: ${NEWS_PAGE_SIZE:10}

logging:
  level:
    root: info
    org.springframework: info
